site_name: VFS Writeup

repo_name: sewer56/vfs-writeup
repo_url: https://github.com/sewer56/vfs-writeup

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sewer56

extra_css:
  - vendor/Reloaded/Stylesheets/reloaded.css

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.blocks.caption
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist
  - def_list
  - meta
  - md_in_html
  - attr_list
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  name: material
  palette:
    scheme: reloaded3-slate
  features:
    - navigation.instant

plugins:
  - search
  - offline
  - exclude-unused-files:
      file_types_to_check: ["psd", "7z", "kra", "avif"]
      file_types_override_mode: append
      enabled: true
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
        remove_comments: true
      cache_safe: true
  - exclude:
      # Exclude the Theme's own files.
      glob:
        - Reloaded/docs/Pages/private/*
        - Reloaded/docs/*.txt
        - Reloaded/.gitignore
        - Reloaded/Readme.md
        - Reloaded/LICENSE
        - Reloaded/*.yml
        - Reloaded/*.py
        - Reloaded/venv/*

nav:
  - Home: index.md
  - FileSystem Architecture: Filesystem-Architecture.md
  - Implementation Strategy: Implementation-Strategy.md
  - Behaviours: Behaviours.md
  - Technology Integrations:
      - DirectStorage & IoRing: Technology-Integrations/DirectStorage.md
      - DLL Hijacking: Technology-Integrations/DLL-Hijacking.md
      - Memory Map Hooking: Technology-Integrations/Memory-Map-Hooking.md
  - Virtual FileSystem:
      - About: Virtual-FileSystem/About.md
      - Usage:
          - From Reloaded: Virtual-FileSystem/Usage/From-Reloaded.md
          - As Standalone: Virtual-FileSystem/Usage/As-Standalone.md
      - Programmer Usage:
          - API Reference: Virtual-FileSystem/Programmer-Usage/API-Reference.md
          - Usage from Reloaded3: Virtual-FileSystem/Programmer-Usage/Usage-Reloaded3.md
          - Usage as Standalone Library: Virtual-FileSystem/Programmer-Usage/Usage-Standalone.md
      - Performance: Virtual-FileSystem/Performance.md
      - Implementation Details:
          - Trees: Virtual-FileSystem/Implementation-Details/Trees.md
          - Optimizations: Virtual-FileSystem/Implementation-Details/Optimizations.md
  - File Emulation Framework:
      - About: File-Emulation-Framework/About.md
      - Routing: File-Emulation-Framework/Routing.md
      - Read Performance: File-Emulation-Framework/Read-Performance.md
      - Emulator Development:
          - Implementing Emulator: File-Emulation-Framework/Emulator-Development/Implementing-Emulator.md
          - Guidelines: File-Emulation-Framework/Emulator-Development/Guidelines.md
          - Emulator API: File-Emulation-Framework/Emulator-Development/Emulator-API.md
          - Framework API: File-Emulation-Framework/Emulator-Development/Framework-API.md
          - Routing: File-Emulation-Framework/Emulator-Development/Routing.md
          - Cookbook: File-Emulation-Framework/Emulator-Development/Emulator-Cookbook.md
      - Implementation Details:
          - Hooks: File-Emulation-Framework/Implementation-Details/Hooks.md
  #- Plugins:
  #    - Nx2VFS: Plugins/Nx2VFS.md
  #    - Archive Emulation Framework: Plugins/Archive-Emulation-Framework.md
